import React, { useState } from 'react';
import { Copy, Download, Plus, Trash2, FileStack, Sparkles, AlertCircle } from 'lucide-react';
import { saveAs } from 'file-saver';
import { Document, Packer, Paragraph, TextRun } from 'docx';

const ExecutiveSummary = () => {
  const [inputs, setInputs] = useState(['']);
  const [output, setOutput] = useState('');
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);

  const addInputField = () => {
    setInputs([...inputs, '']);
  };

  const removeInputField = (index) => {
    if (inputs.length > 1) {
      const newInputs = inputs.filter((_, i) => i !== index);
      setInputs(newInputs);
    }
  };

  const handleInputChange = (index, value) => {
    const newInputs = [...inputs];
    newInputs[index] = value;
    setInputs(newInputs);
  };

  const generateSummary = async () => {
    const validInputs = inputs.filter(input => input.trim());
    if (validInputs.length === 0) return;
    
    setLoading(true);
    setOutput('');
    
    // Simulate AI processing - YOUR PROMPT WILL GOVERN OUTPUT HERE
    // This is just placeholder infrastructure
    setTimeout(() => {
      // YOUR PROMPT LOGIC GOES HERE
      // This is purely infrastructure wiring
      const sampleOutput = `[EXECUTIVE SUMMARY GENERATED BY YOUR PROMPT]
      
Placeholder for AI-generated executive summary based on ${validInputs.length} finding(s).
Your prompt logic will determine the exact content and format here.

This section demonstrates the infrastructure is wired correctly for:
1. Processing multiple input findings
2. Generating consolidated executive summaries
3. Output formatting and export capabilities

The actual AI content generation will be governed by your specific prompt requirements.`;

      setOutput(sampleOutput);
      setLoading(false);
    }, 2000);
  };

  const copyToClipboard = async () => {
    await navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const exportToWord = async () => {
    const doc = new Document({
      sections: [{
        properties: {},
        children: [
          new Paragraph({
            children: [
              new TextRun({
                text: "Executive Audit Summary",
                bold: true,
                size: 32,
              }),
            ],
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: "\n" + output,
                size: 24,
              }),
            ],
          }),
        ],
      }],
    });

    const blob = await Packer.toBlob(doc);
    saveAs(blob, `executive_summary_${Date.now()}.docx`);
  };

  return (
    <div className="space-y-8">
      {/* Input Section */}
      <div>
        <div className="mb-6">
          <h4 className="text-lg font-semibold text-gray-900 mb-2">Input Audit Findings</h4>
          <p className="text-gray-600">
            Add multiple findings to generate a consolidated executive summary
          </p>
        </div>

        <div className="space-y-4">
          {inputs.map((input, index) => (
            <div key={index} className="relative group">
              <div className="flex items-center justify-between mb-2">
                <div className="flex items-center">
                  <div className="w-6 h-6 flex items-center justify-center bg-gray-100 rounded-lg mr-3">
                    <span className="text-sm font-medium text-gray-700">{index + 1}</span>
                  </div>
                  <span className="text-sm font-medium text-gray-700">
                    Finding #{index + 1}
                  </span>
                </div>
                {inputs.length > 1 && (
                  <button
                    onClick={() => removeInputField(index)}
                    className="p-2 text-gray-500 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors"
                    title="Remove this finding"
                  >
                    <Trash2 className="w-4 h-4" />
                  </button>
                )}
              </div>
              <textarea
                value={input}
                onChange={(e) => handleInputChange(index, e.target.value)}
                className="w-full px-4 py-3 text-sm border border-gray-300 rounded-lg bg-white focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:border-transparent resize-y min-h-[120px] font-mono"
                placeholder={`Describe audit finding #${index + 1}...

Include details about:
• The issue or finding
• Impact and risk level
• Current state or evidence
• Any relevant context or evidence`}
              />
            </div>
          ))}
        </div>

        <button
          onClick={addInputField}
          className="mt-4 px-4 py-2.5 bg-emerald-50 text-emerald-700 font-medium rounded-lg hover:bg-emerald-100 transition-colors flex items-center"
        >
          <Plus className="w-5 h-5 mr-2" />
          Add Another Finding
        </button>

        <div className="mt-4 text-sm text-gray-500">
          {inputs.filter(i => i.trim()).length} of {inputs.length} findings ready for analysis
        </div>
      </div>

      {/* Action Button */}
      <div className="pt-6 border-t border-gray-200">
        <div className="flex items-center justify-between">
          <div className="text-sm text-gray-600">
            Ready to generate executive summary
          </div>
          <button
            onClick={generateSummary}
            className="px-6 py-3.5 bg-gradient-to-r from-emerald-600 to-emerald-700 text-white font-semibold rounded-lg hover:from-emerald-700 hover:to-emerald-800 focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed transition-all duration-200 shadow-lg hover:shadow-xl flex items-center"
            disabled={inputs.filter(i => i.trim()).length === 0 || loading}
          >
            {loading ? (
              <>
                <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin mr-3"></div>
                Generating Summary...
              </>
            ) : (
              <>
                <Sparkles className="w-5 h-5 mr-3" />
                Generate Executive Summary
              </>
            )}
          </button>
        </div>
      </div>

      {/* Output Section */}
      {output && (
        <div className="mt-10 pt-8 border-t border-gray-200 animate-fade-in">
          <div className="flex items-center justify-between mb-6">
            <div>
              <h4 className="text-xl font-bold text-gray-900 flex items-center">
                <FileStack className="w-6 h-6 text-emerald-600 mr-3" />
                Executive Summary Output
              </h4>
              <p className="text-gray-600 mt-1">AI-generated from {inputs.filter(i => i.trim()).length} finding(s)</p>
            </div>
            <div className="flex space-x-3">
              <button
                onClick={copyToClipboard}
                className="px-4 py-2.5 bg-gray-100 text-gray-800 font-medium rounded-lg hover:bg-gray-200 transition-colors flex items-center"
              >
                <Copy className="w-4 h-4 mr-2" />
                {copied ? 'Copied!' : 'Copy'}
              </button>
              <button
                onClick={exportToWord}
                className="px-4 py-2.5 bg-emerald-600 text-white font-medium rounded-lg hover:bg-emerald-700 transition-colors flex items-center"
              >
                <Download className="w-4 h-4 mr-2" />
                Export .docx
              </button>
            </div>
          </div>

          <div className="bg-gray-50 border border-gray-200 rounded-xl p-6">
            <pre className="whitespace-pre-wrap font-mono text-sm text-gray-800 leading-relaxed">
              {output}
            </pre>
          </div>

          <div className="mt-4 flex items-start text-sm text-gray-500">
            <AlertCircle className="w-5 h-5 text-gray-400 mr-3 flex-shrink-0 mt-0.5" />
            <span>
              This output demonstrates the infrastructure is wired correctly. The actual content will be generated 
              based on your specific prompt requirements and AI configuration.
            </span>
          </div>
        </div>
      )}

      {loading && !output && (
        <div className="mt-10 p-8 bg-gray-50 border border-gray-200 rounded-2xl text-center">
          <div className="inline-flex p-4 bg-emerald-100 rounded-full mb-6">
            <FileStack className="w-8 h-8 text-emerald-600 animate-pulse" />
          </div>
          <h4 className="text-lg font-semibold text-gray-900 mb-3">Generating Executive Summary</h4>
          <p className="text-gray-600 mb-6">
            Analyzing {inputs.filter(i => i.trim()).length} audit finding(s)...
          </p>
          <div className="w-48 h-2 bg-gray-200 rounded-full overflow-hidden mx-auto">
            <div className="h-full bg-emerald-600 rounded-full animate-[progress_2s_ease-in-out]"></div>
          </div>
        </div>
      )}
    </div>
  );
};

export default ExecutiveSummary;