import React, { useState } from 'react';
import { Copy, Download, Sparkles, AlertCircle } from 'lucide-react';
import { saveAs } from 'file-saver';
import { Document, Packer, Paragraph, TextRun } from 'docx';

const SingleFinding = () => {
  const [input, setInput] = useState('');
  const [output, setOutput] = useState('');
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);

  const generateSeniorLevel = async () => {
    if (!input.trim()) return;
    
    setLoading(true);
    setOutput('');
    
    // Simulate AI processing
    setTimeout(() => {
      // YOUR PROMPT LOGIC WILL DETERMINE OUTPUT
      const sampleOutput = `[SENIOR-LEVEL OUTPUT GENERATED BY YOUR PROMPT]

Placeholder for AI-transformed senior-level language.
Your prompt logic will shape the exact content, tone, and structure.

This demonstrates the infrastructure is correctly wired for:
• Input processing
• AI transformation
• Output formatting
• Export functionality

The actual transformation will be governed by your specific prompt requirements.`;

      setOutput(sampleOutput);
      setLoading(false);
    }, 1500);
  };

  const copyToClipboard = async () => {
    await navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const exportToWord = async () => {
    const doc = new Document({
      sections: [{
        properties: {},
        children: [
          new Paragraph({
            children: [
              new TextRun({
                text: "Senior-Level Audit Finding",
                bold: true,
                size: 32,
              }),
            ],
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: "\n" + output,
                size: 24,
              }),
            ],
          }),
        ],
      }],
    });

    const blob = await Packer.toBlob(doc);
    saveAs(blob, `audit_finding_${Date.now()}.docx`);
  };

  return (
    <div className="space-y-8">
      {/* Input Section */}
      <div>
        <div className="mb-6">
          <h4 className="text-lg font-semibold text-gray-900 mb-2">Input Audit Finding</h4>
          <p className="text-gray-600">
            Enter a detailed audit finding to transform into senior-level language
          </p>
        </div>

        <textarea
          value={input}
          onChange={(e) => setInput(e.target.value)}
          className="w-full px-4 py-3 text-sm border border-gray-300 rounded-lg bg-white focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent resize-y min-h-[200px] font-mono"
          placeholder={`Paste your detailed audit finding here...

Include as much context as possible:
• Detailed finding description
• Current controls or safeguards
• Risk assessment and impact
• Affected systems or processes
• Any supporting evidence or data
• Current state or status`}
        />
        
        <div className="mt-3 text-sm text-gray-500">
          Provide comprehensive details for optimal transformation
        </div>
      </div>

      {/* Action Button */}
     <div className="pt-6 border-t border-gray-200">
        <div className="flex items-center justify-between">
          <div className="text-sm text-gray-600">
            Ready to generate executive summary
          </div>
        <button
          onClick={generateSeniorLevel}
     className="px-6 py-3.5 bg-gradient-to-r from-emerald-600 to-emerald-700 text-white font-semibold rounded-lg hover:from-emerald-700 hover:to-emerald-800 focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed transition-all duration-200 shadow-lg hover:shadow-xl flex items-center"
          disabled={!input.trim() || loading}
        >
          {loading ? (
            <>
              <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin mr-3"></div>
              Transforming Finding...
            </>
          ) : (
            <>
              <Sparkles className="w-5 h-5 mr-3" />
              Generate Senior-Level Version
            </>
          )}
        </button>
      </div>
     </div>

      {/* Output Section */}
      {output && (
        <div className="mt-10 pt-8 border-t border-gray-200 animate-fade-in">
          <div className="flex items-center justify-between mb-6">
            <div>
              <h4 className="text-xl font-bold text-gray-900 flex items-center">
                <Sparkles className="w-6 h-6 text-primary-600 mr-3" />
                Senior-Level Output
              </h4>
              <p className="text-gray-600 mt-1">AI-transformed for executive audience</p>
            </div>
            <div className="flex space-x-3">
              <button
                onClick={copyToClipboard}
                className="px-4 py-2.5 bg-gray-100 text-gray-800 font-medium rounded-lg hover:bg-gray-200 transition-colors flex items-center"
              >
                <Copy className="w-4 h-4 mr-2" />
                {copied ? 'Copied!' : 'Copy'}
              </button>
              <button
                onClick={exportToWord}
                className="px-4 py-2.5 bg-primary-600 text-white font-medium rounded-lg hover:bg-primary-700 transition-colors flex items-center"
              >
                <Download className="w-4 h-4 mr-2" />
                Export .docx
              </button>
            </div>
          </div>

          <div className="bg-gray-50 border border-gray-200 rounded-xl p-6">
            <pre className="whitespace-pre-wrap font-mono text-sm text-gray-800 leading-relaxed">
              {output}
            </pre>
          </div>

          <div className="mt-4 flex items-start text-sm text-gray-500">
            <AlertCircle className="w-5 h-5 text-gray-400 mr-3 flex-shrink-0 mt-0.5" />
            <span>
              This output demonstrates the infrastructure is wired correctly. The actual transformation 
              will be governed by your specific prompt requirements and AI configuration.
            </span>
          </div>
        </div>
      )}

      {loading && !output && (
        <div className="mt-10 p-8 bg-gray-50 border border-gray-200 rounded-2xl text-center">
          <div className="inline-flex p-4 bg-primary-100 rounded-full mb-6">
            <Sparkles className="w-8 h-8 text-primary-600 animate-pulse" />
          </div>
          <h4 className="text-lg font-semibold text-gray-900 mb-3">Transforming Your Finding</h4>
          <p className="text-gray-600 mb-6">
            Analyzing and converting to senior-level language...
          </p>
          <div className="w-48 h-2 bg-gray-200 rounded-full overflow-hidden mx-auto">
            <div className="h-full bg-primary-600 rounded-full animate-[progress_1.5s_ease-in-out]"></div>
          </div>
        </div>
      )}
    </div>
  );
};

export default SingleFinding;